elasticsearch:
  host: 3.37.127.238
  port: 9200

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

  batch:
    job:
      enabled: falseㅈ

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.type: trace
