version: "3.7"

services:
  app:
    container_name: app
    image: adoptopenjdk/openjdk11
    ports:
      - "8080:8080"
    restart: always
    build: .
    networks:
      - monitoring
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - /Users/kobeomseok95/Desktop/study/playground/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on: 
      - app
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge

