INSERT INTO POST_ENTITY(POST_ID, TITLE) VALUES (1, '1번째 게시글');

INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (1, 8, 1, '1번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (2, 4, 1, '2번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (3, 10, 1, '3번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (4, 9, 1, '4번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (5, 6, 1, '5번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (6, 2, 1, '6번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (7, 1, 1, '7번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (8, 7, 1, '8번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (9, 3, 1, '9번째 댓글');
INSERT INTO COMMENT_ENTITY(COMMENT_ID, REAL_ORDER, POST_ID, TEXT) VALUES (10, 5, 1, '10번째 댓글');
