server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:yeolgongdabang
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug