INSERT INTO POST(POST_ID, TITLE) VALUES (1, '1번째 게시글');

INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (8, 1, '8번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (4, 1, '4번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (10, 1, '10번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (9, 1, '9번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (6, 1, '6번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (2, 1, '2번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (1, 1, '1번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (7, 1, '7번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (3, 1, '3번째 댓글');
INSERT INTO COMMENT(COMMENT_ID, POST_ID, TEXT) VALUES (5, 1, '5번째 댓글');
