INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[당일권] 2시간', 3000, 2);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[당일권] 4시간', 5000, 4);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[당일권] 6시간', 7000, 6);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[당일권] 8시간', 9000, 8);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[당일권] 12시간', 12000, 12);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[당일권] 1시간 연장', 1500, 1);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[기간권] 2주', 80000, 336);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[기간권] 4주', 140000, 672);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[시간권] 50시간', 140000, 50);
INSERT INTO voucher (VOUCHER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PASS_NAME, PRICE, TIME)
VALUES (10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '[시간권] 100시간', 140000, 100);