spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      format_sql: true
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 3
    url: jdbc:mysql://localhost:3306/flyway?serverTimezone=UTC&characterEncoding=UTF-8
    user: root
    password:
